import Head from 'next/head'
import Layout from "@/components/layout";
import Image from "next/image";

export default function Main({ metaTitle, metaDescription, children }) {
  return (
    <div>
      <Head>
        <title>Create Next App - {metaTitle}</title>
        <meta
          name="description"
          content={metaDescription || "Generated by create next app"}
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout metaTitle="Home">
        <p>Home</p>
        <Image src="/next.png" width={400} height={400} alt="next image" />
        <img src="/next.png" width={400} height={400} alt="next image" />
      </Layout>

    </div>
  );
}
